Switch off TopUp ETs for RCC PML ATC, Switch on TopUpStable ETs for RCC PML ATC
lidofinance/scripts pull request #188
Opened 2023-10-20 11:19 UTC by kovalgek

#### WHAT

#### HOW

2023-10-20 17:06 UTC, BATMAH69 commented
> @rkolpakov @BATMAH69 Hey folks, can you point out the new factories and briefly uncover the details about their connection?

I don't have information about it but @rkolpakov have

2023-10-24 06:58 UTC, TheDZhon requested changes
:eyes:

2023-10-24 06:58 UTC, TheDZhon commented on scripts/vote_2023_10_31.py
> +        # 1. Switch off TopUp ETs for RCC PML ACT
There should be finance limits update:
https://github.com/lidofinance/scripts/blob/33034fe893a190991ee26e30c3118789feb5dedd/archive/scripts/vote_2022_12_06_1.py#L61-L102

see: https://discord.com/channels/761182643269795850/1163831729635733574/1166262759630061588
and https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-13.md

2023-10-24 07:01 UTC, TheDZhon commented
Let's add new ABIs to the PR @kovalgek :pray:

2023-10-25 14:13 UTC, TheDZhon commented
Fixed the acceptance and regression tests that were failing due to the NO-1 offboarding.

![image](https://github.com/lidofinance/scripts/assets/961317/8f08efda-0d0f-4345-8a6e-27aef359b67a)

2023-10-26 13:53 UTC, zuzueeka commented on scripts/vote_2023_10_31.py
> +        # with limits: 1000 ETH, 1000 stETH, 5M LDO, 2M DAI, 2M USTD, 2M USDC
typo: USTD -> USDT

2023-10-27 08:28 UTC, zuzueeka commented on scripts/vote_2023_10_31.py
> +            reference="Fund Gas Funder multisig"
Fund RCC multisig

2023-10-27 08:28 UTC, zuzueeka commented on scripts/vote_2023_10_31.py
> +            reference="Fund Gas Funder multisig"
Fund PML multisig

2023-10-27 08:28 UTC, zuzueeka commented on scripts/vote_2023_10_31.py
> +            reference="Fund Gas Funder multisig"
Fund ATC multisig

2023-10-27 08:44 UTC, zuzueeka commented on tests/test_2023_10_31.py
> +
Could you please add tests for stETH payments?
1. agent’s balance has decreased by the expected number. 
2. multisig balances increased by expected amounts.
3. agent delta = sum of multisig deltas.

2023-10-27 08:44 UTC, zuzueeka commented on tests/test_2023_10_31.py
> +    assert rcc_already_spent_amount == 800000000000000000000000
It seems to me better to check the equality of the parameters before the vote
like:
rcc_already_spent_amount_before == rcc_already_spent_amount_after == 800000000000000000000000

2023-10-27 08:44 UTC, zuzueeka commented on tests/test_2023_10_31.py
> +# todo: move to utils
it's already in scripts/utils/test/easy_track_helpers.py

2023-10-27 14:41 UTC, bulbozaur commented
Can't see 4th action in script 
iV. Change the on-chain name of node operator with id 27 from 'Prysmatic Labs' to 'Prysm Team at Offchain Labs'

2023-10-27 14:54 UTC, bulbozaur commented on tests/test_2023_10_31.py
> +    assert not has_payments_permission(contracts.acl, contracts.finance, permission.entity, usdt["address"], ldo_holder.address, usdt["limit"])
Why are usdt and usdc permissions check with not?

2023-10-30 09:24 UTC, kovalgek commented
> Can't find 4th action in script iV. Change the on-chain name of node operator with id 27 from 'Prysmatic Labs' to 'Prysm Team at Offchain Labs'

We decided to skip it for this voting. https://discord.com/channels/761182643269795850/1166003540884455456/1167133297227337779

2023-10-31 11:20 UTC, zuzueeka commented on tests/test_2023_10_31.py
> +    steth_balance_checker(dao_balance_before - dao_balance_after, 1 * (10**18) + 1 * (10**18) + 1 * (10**18))
why is it an explicit quantity and not the sum of the previous parameters?

2023-10-31 11:24 UTC, bulbozaur commented on scripts/vote_2023_10_31.py
> +        encode_permission_grant(
<img width="482" alt="Screenshot 2023-10-31 at 14 22 17" src="https://github.com/lidofinance/scripts/assets/870356/9a5fd5f6-0c7b-42a6-8875-f269b178d1e3">
Agent already have MANAGE_NODE_OPERATOR_ROLE on Node Operators registry, so you have only to call set name method with agent forward method

2023-11-07 11:23 UTC, closed without merging