Pectra Devnet4 voting script
lidofinance/scripts pull request #329
Opened 2024-12-19 19:29 UTC by Amuhar

2025-01-29 14:19 UTC, AlexandrMov commented on scripts/before_pectra_upgrade.py
> +            "8. Update CSFeeOracle consensus version to 3",
Will it be received from `CS_FEE_ORACLE_CONSENSUS_VERSION`?
```suggestion
            "8. Update CSFeeOracle consensus version to 2",
```

2025-01-29 14:22 UTC, Amuhar commented on scripts/before_pectra_upgrade.py
> +            "8. Update CSFeeOracle consensus version to 3",
right, it should be 2. Thank you!

2025-02-10 12:10 UTC, avsetsin commented on tests/test_before_pectra_upgrade_holesky.py
> +            recievers=[Contract("0x96d2Ff1C4D30f592B91fd731E218247689a76915")],
consider using a constant for this address

2025-02-10 12:13 UTC, avsetsin commented on tests/test_before_pectra_upgrade_holesky.py
> +    validate_permission_grant_event(events[12], permission)
events[11] is not checked

2025-02-10 12:16 UTC, avsetsin commented on utils/config.py
> +    from configs.config_devnet4 import *
I guess it can be removed as we do not include devnet4 config in the PR

2025-02-18 21:10 UTC, Psirex commented on scripts/before_pectra_upgrade_holesky.py
> +            "19. Grant PAUSE_ROLE on WithdrawalQueue 0xc7cc160b58F8Bb0baC94b80847E2CF2800565C50 to the new GateSeal 0xAE6eCd77DCC656c5533c4209454Fd56fB46e1778",
Descriptions in items 19–22 contain `&nbsp;` instead of regular spaces. Is this intentional?

2025-04-10 13:44 UTC, avsetsin commented on scripts/vote_23_04_2025.py
> +"""
I would suggest the next description:

---

Upgrade the Oracle components and replace the CS Verifier contract to ensure compatibility with the upcoming Ethereum Pectra hardfork, as outlined in [LIP-27](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-27.md) and discussed [on the forum](https://research.lido.fi/t/lip-27-ensuring-compatibility-with-ethereum-s-pectra-upgrade/9444).

1. **Increment the consensus versions** for the following oracle contracts:
   - Accounting Oracle: v2 → v3
   - Validator Exit Bus Oracle: v2 → v3
   - CSM Fee Oracle: v1 → v2  
   
   This enables the use of a new algorithm that ensures correct oracle behavior before and after the Pectra hardfork. Items 1–9.

2. **Replace the CS Verifier contract** with a new implementation compatible with the Pectra hardfork.  
   The new contract removes slashing report functionality and reflects the updated gIndex structure. Items 10-11.

Proposal approved on [Snapshot](https://snapshot.box/#/s:lido-snapshot.eth/proposal/0xb6559f0cdb1164ae5d63769827c4a275805bd944392a17b60cf51ddc54429dc6).

2025-04-10 13:44 UTC, avsetsin commented on scripts/vote_23_04_2025.py
> +4. Grant MANAGE_CONSENSUS_VERSION_ROLE role on Validator Exit Bus Oracle 0x0De4Ea0184c2ad0BacA7183356Aea5B8d5Bf5c6 to Aragon Agent 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
```suggestion
4. Grant MANAGE_CONSENSUS_VERSION_ROLE role on Validator Exit Bus Oracle 0x0De4Ea0184c2ad0BacA7183356Aea5B8d5Bf5c6e to Aragon Agent 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
```

2025-04-10 13:44 UTC, avsetsin commented on scripts/vote_23_04_2025.py
> +            "4. Grant MANAGE_CONSENSUS_VERSION_ROLE role on Validator Exit Bus Oracle 0x0De4Ea0184c2ad0BacA7183356Aea5B8d5Bf5c6 to Aragon Agent 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c",
```suggestion
            "4. Grant MANAGE_CONSENSUS_VERSION_ROLE role on Validator Exit Bus Oracle 0x0De4Ea0184c2ad0BacA7183356Aea5B8d5Bf5c6e to Aragon Agent 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c",
```

2025-04-10 13:44 UTC, avsetsin commented on utils/config.py
> +    return voting.voteTime() + voting.objectionPhaseTime()
Just `voting.voteTime()` is enough. Objection phase already included in the voteTime

See here for details:
https://github.com/lidofinance/aragon-apps/blob/master/apps/voting/contracts/Voting.sol#L769-L780

2025-04-11 07:23 UTC, avsetsin approved these changes
lgtm!

2025-04-14 09:01 UTC, kate-aleksseeva requested changes

2025-04-15 08:22 UTC, iamnp approved these changes

2025-04-15 08:22 UTC, iamnp commented on utils/test/easy_track_helpers.py
> -        skip_time=5 * 60 * 60 * 24,
Why this change is needed?

2025-04-15 08:22 UTC, iamnp commented on tests/test_23_04_2025.py
> +    validate_consensus_version_update(events[:3], AO_CONSENSUS_VERSION)
Please check the executer contract for all events in this test - refer to the implementation here: https://github.com/lidofinance/scripts/blob/a9c911b78d7f40a1fb3f84568a3ccc5ecd6d08a6/utils/test/event_validators/permission.py#L89

2025-04-15 08:23 UTC, iamnp requested changes
See comments above ^

2025-04-15 08:53 UTC, Amuhar commented on utils/test/easy_track_helpers.py
> -        skip_time=5 * 60 * 60 * 24,
these changes were made in this PR https://github.com/lidofinance/scripts/pull/375
@bulbozaur

2025-04-15 10:45 UTC, kate-aleksseeva commented
Could you please remove the line I’ve linked below?
This vote affects the CSM logic, so we need to run the full test suite.
https://github.com/lidofinance/scripts/blob/bbef6bbd3daa4c65028f6004a5e71dad3cdcc164/tests/regression/test_accounting_oracle_extra_data_full_items.py#L221

2025-04-15 11:22 UTC, iamnp commented
[Commit #1](https://github.com/lidofinance/scripts/pull/329/commits/bc2034dd4d49cbaa0908d9b994286de66dfa04a4): Please add event executor check to **validate_consensus_version_set**
[Commit #2](https://github.com/lidofinance/scripts/pull/329/commits/aeccb73c4aae9af6b4eecb406a0eeb7323ea9d0f): I don't think it is reasonable to do full file formatting in order to remove a test skip line - please omit all the formatting changes

2025-04-15 12:22 UTC, iamnp approved these changes
LGTM!

2025-04-16 10:31 UTC, merged